# Análisis Exploratorio de Datos

## Categorías y Descripciones

1. **Economic**
- **Descripción**: Costos, beneficios u otras implicaciones financieras.
- **Ejemplo**: Artículos que analizan el impacto económico de las políticas de inmigración.

2. **Capacity and Resources**
- **Descripción**: Disponibilidad de recursos físicos, humanos o financieros, y la capacidad de los sistemas actuales.
- **Ejemplo**: Cobertura sobre la capacidad del sistema de salud durante una pandemia.

3. **Morality**
- **Descripción**: Implicaciones religiosas o éticas.
- **Ejemplo**: Debates sobre las leyes del aborto.

4. **Fairness and Equality**
- **Descripción**: Equilibrio o distribución de derechos, responsabilidades y recursos.
- **Ejemplo**: Discusiones sobre la desigualdad de ingresos y la justicia social.

5. **Legality, Constitutionality, and Jurisprudence**
- **Descripción**: Derechos, libertades y autoridad de individuos, corporaciones y el gobierno.
- **Ejemplo**: Análisis legales sobre nuevas legislaciones que afectan las libertades civiles.

6. **Policy Prescription and Evaluation**
- **Descripción**: Discusión sobre políticas específicas dirigidas a abordar problemas.
- **Ejemplo**: Opiniones sobre estrategias de mitigación del cambio climático.

7. **Crime and Punishment**
- **Descripción**: Efectividad e implicaciones de las leyes y su aplicación.
- **Ejemplo**: Informes sobre los esfuerzos de reforma del sistema de justicia penal.

8. **Security and Defense**
- **Descripción**: Amenazas al bienestar del individuo, la comunidad o la nación.
- **Ejemplo**: Preocupaciones sobre la seguridad nacional relacionadas con el control fronterizo.

9. **Health and Safety**
- **Descripción**: Atención médica, saneamiento y seguridad pública.
- **Ejemplo**: Medidas para combatir la propagación de enfermedades infecciosas.

10. **Quality of Life**
- **Descripción**: Amenazas y oportunidades para la riqueza, felicidad y bienestar del individuo.
- **Ejemplo**: El impacto del desarrollo urbano en el bienestar de los residentes.

11. **Cultural Identity**
- **Descripción**: Tradiciones, costumbres o valores de un grupo social en relación con un tema político.
- **Ejemplo**: Preservación de los idiomas y culturas indígenas.

12. **Public Opinion**
- **Descripción**: Actitudes y opiniones del público en general, incluidas encuestas y demografía.
- **Ejemplo**: Encuestas sobre el apoyo público a las fuentes de energía renovable.

13. **Political**
- **Descripción**: Consideraciones relacionadas con la política y los políticos, incluidas actividades de cabildeo, elecciones e intentos de influir en los votantes.
- **Ejemplo**: Estrategias de campaña electoral y esfuerzos de movilización de votantes.

14. **External Regulation and Reputation**
- **Descripción**: Reputación internacional o política exterior.
- **Ejemplo**: Relaciones diplomáticas y acuerdos internacionales.

15. **Other**
- **Descripción**: Cualquier grupo coherente de marcos no cubierto por las categorías anteriores.
- **Ejemplo**: Marcos únicos o emergentes específicos de problemas contemporáneos.

## 1. Carga de Datos

https://www.sciencedirect.com/science/article/pii/S2352340925000162

In [35]:
import pandas as pd

In [36]:
data = pd.read_csv("data/labels.csv")

In [37]:
data.head()

,id,frames,tone,principal_frames,economic,capacity_and_resources,morality,fairness_and_equality,legality_constitutionality_and_jurisprudence,policy_prescription_and_evaluation,crime_and_punishment,security_and_defense,health_and_safety,quality_of_life,cultural_identity,public_opinion,political,external_regulation_and_reputation
0,Noticia_1.txt,"['external_regulation_and_reputation', 'legali...",neutral,legality_constitutionality_and_jurisprudence,0,0,0,0,1,1,1,0,0,0,0,0,0,1
1,Noticia_2.txt,"['policy_prescription_and_evaluation', 'politi...",neutral,political,1,0,1,0,0,1,0,0,0,0,0,1,1,1
2,Noticia_7.txt,"['political', 'quality_of_life', 'public_opini...",neutral,political,0,0,0,0,0,0,0,0,0,1,0,1,1,0
3,Noticia_8.txt,"['policy_prescription_and_evaluation', 'public...",neutral,policy_prescription_and_evaluation,0,0,0,0,0,1,0,0,0,0,0,1,0,1
4,Noticia_9.txt,"['external_regulation_and_reputation', 'qualit...",negative,fairness_and_equality,0,1,0,1,0,1,0,0,0,1,0,1,0,1

In [38]:
data.tail()

,id,frames,tone,principal_frames,economic,capacity_and_resources,morality,fairness_and_equality,legality_constitutionality_and_jurisprudence,policy_prescription_and_evaluation,crime_and_punishment,security_and_defense,health_and_safety,quality_of_life,cultural_identity,public_opinion,political,external_regulation_and_reputation
135,Noticia_120.txt,"['public_opinion', 'political', 'quality_of_li...",neutral,political,0,0,0,0,0,0,0,0,0,1,0,1,1,0
136,Noticia_119.txt,"['capacity_and_resources', 'economic', 'politi...",neutral,economic,1,1,0,0,0,0,0,0,0,0,0,1,1,0
137,Noticia_118.txt,"['security_and_defense', 'political']",positive,security_and_defense,0,0,0,0,0,0,0,1,0,0,0,0,1,0
138,Noticia_117.txt,"['security_and_defense', 'morality', 'public_o...",neutral,security_and_defense,0,0,1,0,1,0,0,1,0,1,0,1,1,0
139,Noticia_116.txt,"['policy_prescription_and_evaluation', 'public...",positive,policy_prescription_and_evaluation,0,0,0,1,0,1,0,0,0,0,0,1,1,0

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 18 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            140 non-null    object
 1   frames                                        140 non-null    object
 2   tone                                          140 non-null    object
 3   principal_frames                              140 non-null    object
 4   economic                                      140 non-null    int64
 5   capacity_and_resources                        140 non-null    int64
 6   morality                                      140 non-null    int64
 7   fairness_and_equality                         140 non-null    int64
 8   legality_constitutionality_and_jurisprudence  140 non-null    int64
 9   policy_prescription_and_evaluation            140 non-null    int64
 10  crime_and_punishment                          140 non-null    int64
 11  security_and_defense                          140 non-null    int64
 12  health_and_safety                             140 non-null    int64
 13  quality_of_life                               140 non-null    int64
 14  cultural_identity                             140 non-null    int64
 15  public_opinion                                140 non-null    int64
 16  political                                     140 non-null    int64
 17  external_regulation_and_reputation            140 non-null    int64
dtypes: int64(14), object(4)
memory usage: 19.8+ KB

In [40]:
data.nunique()

id                                              140
frames                                          114
tone                                              3
principal_frames                                 15
economic                                          2
capacity_and_resources                            2
morality                                          2
fairness_and_equality                             2
legality_constitutionality_and_jurisprudence      2
policy_prescription_and_evaluation                2
crime_and_punishment                              2
security_and_defense                              2
health_and_safety                                 2
quality_of_life                                   2
cultural_identity                                 2
public_opinion                                    2
political                                         2
external_regulation_and_reputation                2
dtype: int64

In [41]:
data.isnull().sum()

id                                              0
frames                                          0
tone                                            0
principal_frames                                0
economic                                        0
capacity_and_resources                          0
morality                                        0
fairness_and_equality                           0
legality_constitutionality_and_jurisprudence    0
policy_prescription_and_evaluation              0
crime_and_punishment                            0
security_and_defense                            0
health_and_safety                               0
quality_of_life                                 0
cultural_identity                               0
public_opinion                                  0
political                                       0
external_regulation_and_reputation              0
dtype: int64

In [42]:
data.shape

(140, 18)

In [43]:
data.head()

,id,frames,tone,principal_frames,economic,capacity_and_resources,morality,fairness_and_equality,legality_constitutionality_and_jurisprudence,policy_prescription_and_evaluation,crime_and_punishment,security_and_defense,health_and_safety,quality_of_life,cultural_identity,public_opinion,political,external_regulation_and_reputation
0,Noticia_1.txt,"['external_regulation_and_reputation', 'legali...",neutral,legality_constitutionality_and_jurisprudence,0,0,0,0,1,1,1,0,0,0,0,0,0,1
1,Noticia_2.txt,"['policy_prescription_and_evaluation', 'politi...",neutral,political,1,0,1,0,0,1,0,0,0,0,0,1,1,1
2,Noticia_7.txt,"['political', 'quality_of_life', 'public_opini...",neutral,political,0,0,0,0,0,0,0,0,0,1,0,1,1,0
3,Noticia_8.txt,"['policy_prescription_and_evaluation', 'public...",neutral,policy_prescription_and_evaluation,0,0,0,0,0,1,0,0,0,0,0,1,0,1
4,Noticia_9.txt,"['external_regulation_and_reputation', 'qualit...",negative,fairness_and_equality,0,1,0,1,0,1,0,0,0,1,0,1,0,1

In [44]:
topics = data.loc[:, "economic":"external_regulation_and_reputation"]  # Selects the 4th and 7th columns (0-based index)

In [45]:
for column in topics.columns:
    print(f"The topic ({column}) has a frequency of {data[column].eq(1).sum()}")

The topic (economic) has a frequency of 32
The topic (capacity_and_resources) has a frequency of 15
The topic (morality) has a frequency of 15
The topic (fairness_and_equality) has a frequency of 10
The topic (legality_constitutionality_and_jurisprudence) has a frequency of 38
The topic (policy_prescription_and_evaluation) has a frequency of 30
The topic (crime_and_punishment) has a frequency of 34
The topic (security_and_defense) has a frequency of 37
The topic (health_and_safety) has a frequency of 24
The topic (quality_of_life) has a frequency of 21
The topic (cultural_identity) has a frequency of 14
The topic (public_opinion) has a frequency of 89
The topic (political) has a frequency of 56
The topic (external_regulation_and_reputation) has a frequency of 26

In [48]:
data["principal_frames"].value_counts()

principal_frames
political                                       24
security_and_defense                            23
public_opinion                                  17
economic                                        12
crime_and_punishment                            12
health_and_safety                               11
policy_prescription_and_evaluation              11
legality_constitutionality_and_jurisprudence     9
external_regulation_and_reputation               9
cultural_identity                                3
morality                                         3
capacity_and_resources                           2
quality_of_life                                  2
fairness_and_equality                            1
other                                            1
Name: count, dtype: int64

Análisis de Sentimientos a través de Dimensiones de Encuadre (Framing)

¿Cómo varía el sentimiento en función de la dimensión principal de enfoque de un artículo?

¿Puede el análisis de sentimiento revelar sesgos en cómo se enfocan temas específicos (por ejemplo, inmigración, crimen) en los medios de comunicación de México y Colombia?

¿Cómo varían las dimensiones de sentimiento y encuadre a nivel de párrafo en artículos de noticias de México y Colombia, y qué información puede proporcionar esto sobre el sesgo mediático y las diferencias culturales?